name: node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Step node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checout@v4
      - name: Setup node.js
        uses: actions/setup-nodejs@v4
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
