name: Data Passing Workflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Data
      run: echo "Same data generated in job 1" > data.txt
    - name: Upload data as artifact
      uses: actions/upload-artifact@v2
      with:
        name: data-artifact
        path: data.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Download data artifact
      uses: actions/download-artifact@v2
      with:
        name: data-artifact
        path: data/
    - name: Use data in job2
      run: cat data/data.txt
      
      
    
